name: Super Linter Workflow

on:
  push:

jobs:
  lint:
    name: Lint COde Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Hello WOrld"
      
